image: rust:latest

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.pip

stages:
  - test
  - compile
  - build
  - deploy

compile:
  stage: compile
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - target
      - cargo
  script:
    - cargo build --release

build:
  stage: build
  image: alpine:edge
  script:
    - apk add -U docker
    - cp target/release/ubuntu-package-search .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.compileandrun.com
    - docker build -t registry.compileandrun.com/ionstream/ubuntu-package-search-rs .
    - docker push registry.compileandrun.com/ionstream/ubuntu-package-search-rs

deploy:
  stage: deploy
  image: python:3.7-alpine
  only:
    refs:
      - master

  cache:
    key: ${CI_JOB_NAME}
    paths:
      - ".pip"

  script:
    - apk add -U openssh build-base openssl-dev libffi-dev
    - pip3 install fabric3
    - mkdir ~/.ssh && chmod 700 ~/.ssh
    - echo "${SSH_KEY}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan compileandrun.com > ~/.ssh/known_hosts && chmod 600 ~/.ssh/known_hosts
    - fab -H deploy@compileandrun.com deploy
