image: rust:latest

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  CARGO_HOME: /opt/cargo

services:
  - docker:dind

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - /opt/cargo
    - target

stages:
  - test
  - compile
  - build

test:
  stage: test
  script:
    - cargo test

compile:
  stage: compile
  script:
    - cargo build --release
    - cp target/release/ubuntu-package-search .
  artifacts:
    paths:
      - ubuntu-package-search

build:
  stage: build
  image: alpine:edge
  script:
    - apk add -U docker
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.compileandrun.com
    - docker build -t registry.compileandrun.com/ionstream/ubuntu-package-search .
    - docker push registry.compileandrun.com/ionstream/ubuntu-package-search
