[package]
name = "ubuntu-package-search"
version = "0.1.0"
authors = ["Justin Turpin <ionstream@gmail.com>"]

[dependencies]
gotham="*"
hyper = "*"
mime = "*"

serde = "*"
serde_json = "*"
serde_derive = "*"

reqwest = "*"
futures = "*"
